import '../styles/dist.css'
import Footer from '@components/organisms/Footer'
import Header from '@components/organisms/Header'

// TODO:turbopack next/font 対応待ち
// const roboto = Roboto({
//   variable: '--roboto-font',
//   weight: '100',
// })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
      // TODO:turbopack next/font 対応待ち
      // className={roboto.variable}
    >
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head>
        <title>steadfast-news</title>
        <meta
          content='width=device-width, initial-scale=1'
          name='viewport'
        />
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.svg'
        />
      </head>
      <body className='text-black'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
